### ISSUE TITLE
How to get the pid of the prerender process

### ISSUE THREAD

**Issue by pessoa** [prerender/prerender#134]
I'd like to write some sort of init script for prerender. For that, I need a way to know its PID so to kill it or something similar on stop command.
How should I do this? Maybe a PR such as:

```
var pid = ""+process.pid; // need to turn into a string
fs.writeFile('/var/run/monitorserver.js.pid', pid, function (err) {
   if (err) throw err;
});
```

**Comment by mrgamer** [comment]
mmm isn't something like an upstart script simpler and way more reliable? (it automatically detects the pid)
I can post a gist with mine if you would like

**Comment by pessoa** [comment]
Thanks! That would be great!

**Comment by mrgamer** [comment]
here it is: https://gist.github.com/mrgamer/6c47bc1dc231e91dd4ce

**Comment by sylido** [comment]
@pessoa Was trying something similar with starting/stopping and also noticed it doesn't kill all the other phantomjs workers. I would suggest just doing `killall node` if you don't have anything node related running on that server, otherwise the upstart thing seems awesome ! Thanks for that one @mrgamer.
