### ISSUE TITLE
Phantom 2.0 support

### ISSUE THREAD

**Issue by mjgp2** [prerender/prerender#160]
Is there ongoing work on this? Otherwise I may have a crack at seeing how easy (or not) it is :)

**Comment by thoop** [comment]
Yep! check out our `phantomjs2` branch. We are using PhantomJS 2 in production based off of that branch.

We have compiled our own PhantomJS 2 from source and are using that until the PhantomJS 2 binaries are available for all platforms and until [medium/phantomjs](https://github.com/medium/phantomjs) upgrades to 2.0.

Just check out the phantomjs2 branch, set PHANTOMJS_CDNURL to the location of your compiled binaries (or leave it if you want to use the phantomjs project's binaries).

Let me know if you have any questions.

**Comment by smarts** [comment]
the `phantomjs2` branch doesn't seem to be working for me on Windows 8.1…

**Comment by jrichard-km** [comment]
the `phantomjs2` branch doesn't seem to be working for me either on OS X Yosemite 10.10.3.
phantom keeps crashing over and over.

To make i work I changed the dependencies (prerender-phantomjs2/package.json) to use
```json
"phantomjs2": "^2.0.0",
````
instead of
```json
"phantomjs": "git+https://github.com/thoop/phantomjs.git#14387f2fe27b0bbc2df097af1c0cb53876cd70a2",
````

Then I change
```js
binary: require('phantomjs').path,
````
to 
```js
binary: require('phantomjs2').path,
````
on line 87 of the file prerender-phantomjs2/lib/server.js

After that I was able to start the server.

**Comment by thoop** [comment]
@smarts It looks like the phantomjs2 windows zip you have isn't unpacking correctly?
```
rror: ENOENT, no such file or directory 'C:\workspace\prerender@cc31d28cb0e850e9cbe8c368
f2e95ed215a39d3f\node_modules\phantomjs\lib\phantom\phantomjs.exe
```

@jrichard-km I've seen that once before where I just had to run a `rm -rf node_modules/` and then re-run `npm install`. Since you added a new package it ran the npm install and probably fixed it. I don't see that we're doing anything different from that package. I'm on the same version of OS X Yosemite.

**Comment by thoop** [comment]
Feel free to open new issues if you continue to run into problems.

**Comment by thoop** [comment]
@jrichard-km It looks like this is due to something with the version of phantomjs2 that ariya uploaded to the official bitbucket repo. It might not be something wrong with the one he uploaded, but it might be set up differently than we expect? We built our own binary and are using that and don't have any issues. The phantomjs2 branch wasn't meant to be used with the current phantomjs 2.0 builds on the official bitbucket.

**Comment by penguin20000** [comment]
@smarts do you eventually solve the issue? I seem to be having the same problem.

**Comment by smarts** [comment]
I did not.

**Comment by aortbals** [comment]
I wanted to post a quick comment about how I'm solving this problem. There are a variety of ways of getting PhantomJS 2.0 installed. On a mac, I would typically install it via `brew install phantomjs`. Deploying phantomjs to a linux server however is a different task entirely. I've opted to remove the dependency on [Medium/phantomjs](https://github.com/Medium/phantomjs) entirely in https://github.com/aortbals/prerender/commit/6e7b46fc6f443dd3455032f4b8be99bde17cf79c. This ends up working well in my scenario because I want complete control over the exact phantomjs binary I have deployed. One example would be installing via an apt repo like https://packagecloud.io/armando/phantomjs.

This degrades the initial user experience of `npm install -g prerender` and it "just working" slightly because you must install `phantomjs` seperately, but makes it much easier to get prerender running on the version of phantomjs you would like.
