### ISSUE TITLE
User agent pasthrough

### ISSUE THREAD

**Issue by hades200082** [prerender/prerender#191]
Hi

We have an issue whereby google mobile tester detects our site as not mobile friendly because pre-render always renders the desktop version.

Is there a way to get prerender to pass through the originally requested useragent to phantom?

Regards

**Comment by thoop** [comment]
We have the ability to support adaptive sites (by passing through the user agent and saving the URLs separately) on our hosted service at Prerender.io. That's not really a feature of the Prerender server since there's more that goes into solving that problem. Email me at todd@prerender.io and I'm happy to turn that on for you if you are using an adaptive site.

If you aren't using an adaptive site, but are using responsive css, then there might be a different issue.
