### ISSUE TITLE
Prerender breaks noscript tag

### ISSUE THREAD

**Issue by NikonNLG** [prerender/prerender#207]
I found that somenow prerender breaks data inside <noscript> tag.
For example, check source for http://render.33slona.net:3000/https://33slona.ru and correct data in https://33slona.ru (search by <noscript> tag)
Is it issue with prerender.io or in some library?

**Comment by thoop** [comment]
Looking into this now.

**Comment by thoop** [comment]
Hi @NikonNLG , it looks like this is due to us using:
```
document.getElementsByTagName('html')[0].outerHTML
```

If you pull out your script tag from your page the same way in Chrome, I'm seeing the Chrome shows it as a string so that's probably why it gets escaped:
![image](https://cloud.githubusercontent.com/assets/1259374/8628482/07909e8e-2719-11e5-9b4d-e6d1e627e455.png)

Since that's how the rendering engine works, we'd have to pull in some type of library to turn that back into html or query the page a different way and make sure it doesn't break anything. I'll put this in our backlog but it's not a high priority issue currently.

**Comment by NikonNLG** [comment]
Hi @thoop 
Thank you! It's not a blocker for our project, so fix it when you will have totally free time. Or, if it will be blocker, I'll send you pull request.
Thanks again for great open-source solution!

**Comment by oscarni** [comment]
Any news on this issue? Is it still in the backlog? We are experiencing this exact issue. Our project would benefit a lot from this being fixed.

**Comment by thoop** [comment]
Sorry, no progress has been made here yet. Since we render the javascript into the full static HTML, even if the crawler doesn't run javascript they can still see the full content of the page. So it shouldn't cause any issues to have the <noscript> tag escaped like that but I agree it isn't helping.
