### ISSUE TITLE
Possible error in lib/server.js

### ISSUE THREAD

**Issue by dalelotts** [prerender/prerender#224]
Looking at line 340, I am wondering if this 

```JavaScript
setTimeout(_.bind(_this.evaluateJavascriptOnPage, _this, req, res), (req.prerender.evaluateJavascriptCheckTimeout || this.evaluateJavascriptCheckTimeout || EVALUATE_JAVASCRIPT_CHECK_TIMEOUT));
```
should be 
```JavaScript
setTimeout(_.bind(_this.evaluateJavascriptOnPage, _this, req, res), (req.prerender.evaluateJavascriptCheckTimeout || _this.evaluateJavascriptCheckTimeout || EVALUATE_JAVASCRIPT_CHECK_TIMEOUT));
```

note the change from  this.evaluateJavascriptCheckTimeout to _this.evaluateJavascriptCheckTimeout

I believe that referring to this rather than _this can cause an exception in some cases.

**Comment by thoop** [comment]
Good catch! It should actually be `_this.options.evaluateJavascriptCheckTimeout`. It wouldn't throw an exception since this.evaluateJavascriptCheckTimeout would always be null and so it would always use the default.

Want to send over a pull request so you get the credit? :) I'm happy to do it otherwise.

Thanks!

**Comment by dalelotts** [comment]
Will do.

**Comment by thoop** [comment]
About to push a fix for this to master. Thanks!
