### ISSUE TITLE
504 for no reason for css files only

### ISSUE THREAD

**Issue by sunshineo** [prerender/prerender#242]
I'm testing locally and the server get 504 for a lot of my css files when my server log shows 200

prerender service log
```
2015-10-14T07:17:22.336Z got 504 in 340ms for static/bower_components/bootstrap/dist/css/bootstrap.css
```
my server log
```
::1 - - [14/Oct/2015:07:17:20 +0000] "GET /static/bower_components/bootstrap/dist/css/bootstrap.css HTTP/1.1" 200 141414 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34 Prerender (+https://github.com/prerender/prerender)"
```

The result is the pre-rendered page looks very ugly because phantom cannot get the css files.

**Comment by sunshineo** [comment]
Sorry. It's my browser try to ask for the css again.

**Comment by LA1CH3** [comment]
@sunshineo could you explain this a little more? I'm having the same issue currently but can't quite figure out how to solve.

**Comment by thoop** [comment]
css files or any other non-html files shouldn't be sent to the prerender server. If you are testing directly against your prerender server like:

`http://prerenderserver.com/http://www.example.com`

Then any relative links from www.example.com will be sent to the prerender server since that's the domain on the request. This is expected and not a problem to see 504s in this case.

Once you proxy the request through your middleware, the relative URLs from the static HTML will be returned from your server so you won't see this issue since the css and other static files will be requested from your domain. If you are seeing css files requested from the prerender server after accessing the page through the middleware, then your middleware might not be set up correctly.

**Comment by sunshineo** [comment]
@thoop said it much better than I could.

**Comment by rainesinternationaldev** [comment]
It looks like I'm having a similar problem in #365, where I get a 404 for failing to load a CSS asset. Any hints in the right direction would be much appreciated!

**Comment by molerat619** [comment]
I have the same issue and it makes sense. 

But how do you proxy the request through the middleware? I have 

`app.use(require('prerender-node').set('prerenderServiceUrl', 'http://localhost:3000'));` 

and request 

`http://localhost:3000/http://localhost:9000/`

 and I get that error.

**Comment by thoop** [comment]
You would request your website like:

http://localhost:9000/?_escaped_fragment_=

And if the middleware is working correctly, that should return a prerendered page.

**Comment by molerat619** [comment]
Right on, so that's what you mean with proxying through the middleware. Maybe it's because I am not a native english-speaker, but I think that is not very clear in the documentation.

Anyway, that worked like a charm - thanks a lot!

**Comment by thoop** [comment]
Sorry! We'll try to make that clearer :)

**Comment by daton89** [comment]
hi, @thoop,

I'm testing the prerender server in my development environment and when the application get assets like *.css or *.svg,jpg or any type of images the prerender server got 400 with the message "invalid url". 
Are you saying that this is the normal behavior? 
I've tested in production and this error not happened.

thank you

**Comment by thoop** [comment]
Are the requests to those URLs relative links? Does it say something like:

```
getting /css/myapp.css
got 400 for /css/myapp.css
```

If so, then yes that is expected behavior. The Prerender server expects a full URL, but your browser will sent a bunch of requests to relative URLs if you are testing directly against a Prerender server in your browser instead of through the middleware on your website.
