### ISSUE TITLE
From hashbang to html5 mode angularjs

### ISSUE THREAD

**Issue by stianlp** [prerender/prerender#257]
Hi!

I am changing from #! to html5 mode in my angularjs application, but I get some issues with prerender.

First I've added both the base tag set to "/" and the meta fragment tag in index.html. In the angularjs app, I've set html5 mode to true and hashPrefix to !. I am serving index.html from all the dynamic routes, and that works fine when browsing.

However, I cannot get prerender to work correctly with Facebook. Take this URL for instance:
https://stian-dot-snap-sale.appspot.com/browse/6265834417684480

It works fine here:
http://service.prerender.io/https://stian-dot-snap-sale.appspot.com/browse/6265834417684480
Although we don't get the css, you can see that the og:image content is the same as the jumpsuit's image url. And the og:title is set to "Jump suit....."

But in the facebook debugger it does not work at all. Head over here and copy pase the url: https://developers.facebook.com/tools/debug/og/object/

Also when trying a hashbang like this, it does not work:
http://service.prerender.io/https://stian-dot-snap-sale.appspot.com/#!/browse/6265834417684480
Isn't this also supposed to work for if someone with a legacy browser shares the hashbang url?

**Comment by thoop** [comment]
You shouldn't use html5 mode and the hashPrefix...you should use one or other other. I would recommend using html5 mode only.

You shouldn't worry about the css or image issues when rendering directly from our service, that's just an issue due to the domain being different from your website. You won't have those issues once proxied through your middleware.

You shouldn't share service.prerender.io URLs anywhere. The URL you should share is `https://stian-dot-snap-sale.appspot.com/browse/6265834417684480` but it doesn't look like you have the middleware installed. Please install the middleware on your platform: https://prerender.io/documentation

Send an email to support@prerender.io if you have any further issues.

**Comment by stianlp** [comment]
In the angularjs documentation, https://docs.angularjs.org/guide/$location, they use the hashPrefix with html5 mode. Not sure why.

Anyways, the middle ware is installed. It works when html5 mode is set to false and hashPrefix = !. But I am trying to move away from  the hashbang.

The reason I shared the service.prerender url was because it works fine there, but it does not work with the facebook crawler.

**Comment by thoop** [comment]
Your middleware isn't working correctly as this URL still returns javascript: https://stian-dot-snap-sale.appspot.com/browse/6265834417684480?_escaped_fragment_=

Please send an email to support@prerender.io to make sure we can help you get set up correctly.
