### ISSUE TITLE
Prerender caching non existent urls

### ISSUE THREAD

**Issue by jsantana90** [prerender/prerender#278]
I'm using the prerender.io service in my angular/node app and have implemented it successfully but I'm getting url cached that do not exist, as in, when I click on the url in the list, it just redirects me to the root url of my website.

![screenshot from 2016-02-11 15 22 49](https://cloud.githubusercontent.com/assets/9933887/12987680/8ad8a868-d0d3-11e5-837a-6267376c0862.png)

The last url is non-existent and shouldn't be cached at all.

How can I fix this?

**Comment by thoop** [comment]
Please send an email to support@prerender.io so we can help you with this. Looks like the crawlers are crawling incorrect URLs and you should use our prerender-satus-code meta tag to return a 404 status code to the crawlers instead of a status code 200. Send us an email and we'll help!

Closing this issue since it doesn't have anything to do with the open source prerender server.
