### ISSUE TITLE
Is it possible to ignore query parameters for caching?

### ISSUE THREAD

**Issue by harianus** [prerender/prerender#282]
We have some urls which we are caching before the user is sharing, like this:

* https://example.com/personal-page/product-124
* https://example.com/personal-page/product-124?utm_source=facebook
* https://example.com/personal-page/product-124?utm_source=twitter

It would be very handy to not have to cache those 3 pages (because they are exactly the same).

Is there a way to do this?

**Comment by thoop** [comment]
We have this implemented on our hosted service but not in the open source version since we have a web UI where you enter URL Parameters to ignore and then those get pulled into the Prerender server.

It's pretty easy to do using `url.parse(req.prerender.url, true)` by deleting any query parameters that match the ones you want to ignore. You'd want to do it in a plugin and modify `req.prerender.url` in the `beforePhantomRequest` or `onPhantomPageCreate` plugin event.

**Comment by harianus** [comment]
Thanks @thoop!

I was able to build the plugin as you said:

```js
// lib/plugins/removeQueryParams.js
var url = require('url');

module.exports = {
    beforePhantomRequest: function(req, res, next) {
        var urlWithoutQuery = req.prerender.url.split('?').shift();
        req.prerender.url = urlWithoutQuery;
        next();
    }
};
```

And by adding this line to `server.js`:

```js
server.use(prerender.removeQueryParams());
```

Is it worth a PR for this plugin?

**Comment by thoop** [comment]
Sometimes URLs with `#!` can have the ? before the `#!` so just doing a split on `?` you might drop the rest of the entire URL if it's formatted that way. If you are using html5 push state this might work but it might not work for `#!` URLs.

Also, removing _all_ query params is less likely scenario than just removing certain query parameters so we'd probably want this plugin to be more advanced to merge it. Thanks though!
