### ISSUE TITLE
Question about prerenderReady

### ISSUE THREAD

**Issue by graemehoffman** [prerender/prerender#314]
I'm working in an angular environment and am having trouble getting prerender to wait long enough to get the correct version of my page. 

During the page setup, after the base asset loads, there are multiple Ajax calls and then some addition image retrieval. The idea is to wait until these images are loaded (I actually need the image width/height for OG tags) and then ask prerender to come and get the page.

In the body of the page I have the following code at the bottom.

`<script> window.prerenderReady = false; </script>`

In my JS, after a bunch of ajax calls, I have the following

`
var img = new Image();
img.onload = function() {
	window.prerenderReady = true;
}
img.src = "Some Image URL";
`
The problem is that prerender captures the page before the image is loaded. 

Any thoughts on how I can fix this?

Thanks

**Comment by thoop** [comment]
Sorry for the delay! By default, we set our PhantomJS up so that we don't load images. If you are waiting for images to download, then that might be the issue there. Any way you can do that without downloading the images? If you are running your own Prerender server you can turn on the rendering of images by default.

**Comment by that1guy** [comment]
@thoop @graemehoffman I'm suffering from the exact same issue here.  And at this point we are still using the prerender.io service (not our own prerender server).

Facebook requires `og:image:width` and `og:image:height` metatags and in order to get these dimensions I need to wait for only one of my images to download.  Here's my code:

```
    //If property has images then set it's metatags for Facebook and Twitter.
    if($scope.property.images.length) {

      ngMeta.setTag('twitter:image', $scope.property.images[0].location);
      ngMeta.setTag('og:image', $scope.property.images[0].location);

      //Facebook needs image dimensions so we wait for image to load then populate.. this sucks.
      var metaImage = new Image();
      metaImage.onload = function () {
        ngMeta.setTag('og:image:width', this.width);
        ngMeta.setTag('og:image:height', this.height);
        $window.prerenderReady = true;
      };
      metaImage.src = $scope.property.images[0].location;

    }
```

Notice I'm setting `window.prerenderReady = true` after I have set the `og:image:width` and `og:image:height` metatags.  Fore some reason the page is still prerendered while `window.prerenderReady` is `false`.

Thanks for help!

**Comment by thoop** [comment]
`window.prerenderReady` is just used as a signal to tell us to wait longer when rendering the page. If it doesn't get set to true then we timeout after 20 seconds and save the page as-is. If we aren't loading images then waiting longer won't change that.

Is there anything else that can be done there? Are you able to cache those values so that you don't have to download the entire image?

**Comment by thoop** [comment]
Feel free to reopen if you have any more info here so that we can help. If you want to enable image loading then you'll need to run Prerender on your own servers.

**Comment by vireneponym** [comment]
Enabling images by setting parameter in lib/server.js does not seem to be working. Any other config we should look at?

**Comment by thoop** [comment]
Can you send a URL that you are testing to support@prerender.io? That way we can try some things and see what's going on.

**Comment by ccqgithub** [comment]
@thoop why not use a signal to tell that the page is ready and can response 200 ? when the page load, we set the signal false to wait for response, until it is be set to true agin ...before your explain, i think `window.prerenderReady` is do that thing...
