### ISSUE TITLE
Prerender not giving prerendered pages when running with _escaped_fragment_= or Open Graph Object Debugger

### ISSUE THREAD

**Issue by swati615** [prerender/prerender#319]
I have a site running on Amazon elastic beanstalk using Nodejs. On another EC2 instance I have setup prerender as given here https://prerender.io/documentation.

I have also added the required path in my node server:

`app.use(require('prerender-node').set('prerenderServiceUrl','http://myprerenderserverpath:8080'));`
When I run: http://myprerenderserverpath:8080/http://example.com/somepage

I get the prerendered pages correctly. The logs show:

```
getting images/logo.png
getting images/loader.gif
getting images/favicon.ico
...
```
and so on based on what images are there on the page.

But when I run the same using http://example.com/somepage/?_escaped_fragment_=

I get the following logs:

```
getting http://example.com/somepage
got 200 in 10311ms for http://example.com/somepage
```
and exactly the same when I run Facebook Open Graph Object Debugger.

So my pages are not getting crawled.

What could the issue be?

**Comment by thoop** [comment]
The requests to relative URLs like "images/logo.png" are just due to loading `http://myprerenderserverpath:8080/http://example.com/somepage` in your browser.

So any relative URLs from your website, your browser will try to load them from `http://myprerenderserverpath:8080/images/logo.png`.

Your static files shouldn't be loaded through prerender as those should just be served from your server directly.

What you sent from your logs actually looks correct.

**Comment by thoop** [comment]
Hmm it shouldn't take 10 seconds unless there's some kind of issue going on there. Do you mind emailing me your full URL? todd@prerender.io

**Comment by thoop** [comment]
Feel free to reopen if you have more info so that we can test here. Thanks!
