### ISSUE TITLE
Google's "_escaped_fragment_" is not recommended anymore

### ISSUE THREAD

**Issue by JHGitty** [prerender/prerender#332]
The README contains this line:
``Prerender adheres to google's _escaped_fragment_ proposal, which we recommend you use.``

As I understand this is no longer valid. Google has deprecated their old AJAX crawling scheme on October 14, 2015: https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html

So Google does not need the `_escaped_fragment_` proposal anymore, right?

**Comment by thoop** [comment]
Google still crawls using the escaped fragment crawling protocol and we still recommend to serve prerendered pages to Google using it.

Some of our customers have tried to let Google execute their javascript and they have found that Google slows their crawl speed way down when executing the javascript themselves. So for medium/large websites that need to be crawled a lot, it's still recommended to serve prerendered pages to Google in order for Google to crawl through your website at a very fast rate.

Feel free to reopen if you have any questions about that.

**Comment by NitroBAY** [comment]
Yeah with Google having deprecated _escaped_fragment_ which you seem to be so proud to have adhered to and the first sentence "Google, Facebook, Twitter, Yahoo, and Bing are constantly trying to view your website... but they don't execute javascript." when Google says that actually now it's okay, that Googlebot can use JS, it's very confusing for me.
And so the bottom line is, based on your message, that now prerender.io is useful with Google (which has pretty much a monopoly in the country I'm about to publish my website) only if you have a website large enough because Google may slow down the crawl rate when it has to execute Javascript. But then don't you think you should say that prerender.io is now useful (for Google I don't know for others) for this very precise use case instead of saying that Google cannot execute Javascript ?

**Comment by thoop** [comment]
Yeah we need to change that. I'm not aware of any published tests showing how well Google can execute and index javascript heavy Single Page Applications of different sizes of websites. Most things I've seen are just one-off tests of a few pages. For that reason, and since Google still crawls the `_escaped_fragment_` protocol, we still recommend you use it. Feel free to test Google's execution of javascript on your site and report back!

**Comment by NitroBAY** [comment]
Yeah okay sure. Javascript support by bots (notably by the one of bing) seems to me to be a very important subject especially now that client side support is more and more used and yet I struggle to fetch informations about it... The website I'm about to launch is most likely not going to be updated a lot. But from my understanding I could still need to use a prerender service depending on Google/Bing' (even though it's a minor web browser I may wanna support it) JS support. Am I right about the current state of JS SEO ?

**Comment by thoop** [comment]
That's correct. Google is working towards complete javascript execution/indexation but none of the other search engines or social networks seem to be executing javascript for SPAs yet. Bing can execute some javascript but we haven't seen them index any javascript frameworks correctly yet without Prerender.

**Comment by NitroBAY** [comment]
Oh okay. I've been struggling finding informations about this.

**Comment by Hyperblaster** [comment]
Running 100+ websites on our platform all entirely built with Angular JS and using Prerender and i can confirm that we have great SEO results currently with the prerender service and terrible results without it. 

It is still definitely the best approach outside of serverside rendering

**Comment by correias** [comment]
How do I remove      ?_escaped_fragment_=   from the URL of my website ,please thanks .

**Comment by thoop** [comment]
Just remove the `<meta name="fragment" content="!">` tag from your pages and Google won't request the `?_escaped_fragment_=` URLs anymore.

**Comment by zhanzizhen** [comment]
_escaped_fragment_ is **deprecated**
https://developers.google.com/search/docs/ajax-crawling/docs/specification
