### ISSUE TITLE
Prerender crashes every 3 hours or so

### ISSUE THREAD

**Issue by DanielFitzgerald** [prerender/prerender#357]
We have Prerender running on a box with 16 cores and 31gb of RAM. It crashes every 3 hours or so
![prerender](https://cloud.githubusercontent.com/assets/5766083/19559264/e4e71ace-96c6-11e6-93d6-e2bcfed3c091.png)

Our configuration is as follows;

```
var prerender = require('./lib');
var os = require('os');

process.env.PAGE_TTL = 259200;

var server = prerender({
    workers: os.cpus().length,
    iterations: 120
});


server.use(prerender.sendPrerenderHeader());
server.use(prerender.blacklist());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
server.use(require('prerender-redis-cache'));
server.start();
```

CPU load and RAM is consistently under 50% until it crashes.

Any idea why this might be happening and why it is at regular intervals? Our site is quite consitently busy and this is killing us SEO wise.

Thanks

**Comment by thoop** [comment]
Thanks for sending that over. Can you provide any more info on the crash you are experiencing? Is it a worker that is crashing? Does Prerender restart the worker after the crash? Or is the entire process crashing without a restart? Is there an error on the console when that happens?

I'd suggest setting the [soft iterations](https://github.com/prerender/prerender#softiterations) parameter to something like 15 so that each worker will try to restart itself often if there are no requests in flight. Leave your normal iterations like you have it so that it will still restart itself in the case that soft iterations can't restart the server if there is always a request in flight.

How many requests per minute are you sending to that machine and what's the cache hit vs miss ratio since you are using a redis cache?

**Comment by DanielFitzgerald** [comment]
From looking at the logs both workers and phantom crashes.

`2016-10-21T07:09:19.299Z worker 15 died, restarting!`

`2016-10-21T07:09:26.275Z worker 17 died, restarting!`

`2016-10-21T07:29:26.146Z worker 198 died, restarting!`

Should there not be an equal number of workers to cores?

Also;

```
2016-10-21T07:28:59.971Z phantom crashed, restarting...
2016-10-21T07:28:59.971Z starting phantom on port [12498]
2016-10-21T07:29:00.169Z started phantom
```
Phantom crashes regularly.

Below are the bandwidth stats before it stopped serving traffic.

![prerender](https://cloud.githubusercontent.com/assets/5766083/19593579/2e3ac79a-9779-11e6-9115-4978cf3bd040.png)

Thanks

**Comment by DanielFitzgerald** [comment]
Adding softIterations only seems to make it crash more regularly

**Comment by DanielFitzgerald** [comment]
Also getting following errors in kernel log

```
Oct 21 09:31:43 prerender-002 kernel: [12268443.092524] traps: phantomjs[2185] general protection ip:f5d7a0 sp:7fff24115830 error:0 in phantomjs[400000+228e000]
Oct 21 09:31:44 prerender-002 kernel: [12268444.290527] traps: phantomjs[2133] general protection ip:f5d7a0 sp:7fffedabb790 error:0 in phantomjs[400000+228e000]
Oct 21 09:31:58 prerender-002 kernel: [12268458.508866] traps: phantomjs[2343] general protection ip:f5d7a0 sp:7fffdf04a0d0 error:0 in phantomjs[400000+228e000]
Oct 21 09:32:07 prerender-002 kernel: [12268466.742643] traps: phantomjs[2453] general protection ip:f5d7a0 sp:7fff66d2a8a0 error:0 in phantomjs[400000+228e000]
Oct 21 09:31:58 prerender-002 kernel: [12268458.508866] traps: phantomjs[2343] general protection ip:f5d7a0 sp:7fffdf04a0d0 error:0 in phantomjs[400000+228e000]
Oct 21 09:32:07 prerender-002 kernel: [12268466.742643] traps: phantomjs[2453] general protection ip:f5d7a0 sp:7fff66d2a8a0 error:0 in phantomjs[400000+228e000]
Oct 21 09:32:18 prerender-002 kernel: [12268477.947317] traps: phantomjs[2525] general protection ip:f5d7a0 sp:7fffa775e4a0 error:0 in phantomjs[400000+228e000]
Oct 21 09:32:24 prerender-002 kernel: [12268483.718674] traps: phantomjs[2317] general protection ip:f5d8c2 sp:7ffffc5e79b0 error:0 in phantomjs[400000+228e000]
Oct 21 09:32:50 prerender-002 kernel: [12268509.809186] traps: phantomjs[3182] general protection ip:f5d7a0 sp:7fff62090fb0 error:0 in phantomjs[400000+228e000]
Oct 21 09:32:57 prerender-002 kernel: [12268517.544077] traps: phantomjs[3129] general protection ip:f5d7a0 sp:7fff8ce218d0 error:0 in phantomjs[400000+228e000]
```

**Comment by thoop** [comment]
The workers dying and PhantomJS crashing is perfectly normal. Setting sofIterations is supposed to make workers kill themselves more often, but they should always be restarted.

It's weird that it just stops serving requests. We don't see that happen on our machines. Which version of Node are you using?

Since you are using the redis cache, that should still be serving pages even if PhantomJS is having trouble. If you aren't seeing the pages served from redis, that means the entire process crashed or might mean redis is having issues. 

After Prerender stops serving pages, are you seeing any console output? Can you paste the last console output you see before it stops working?

**Comment by DanielFitzgerald** [comment]
We are using node 0.10.25.

It completely stops serving pages, so it's the entire process that stops.

There is a longer message when phantom crashes sometimes.

I am getting the logs from our host, I can only SSH in and reading the logs ins a pain. I will post when I have them.

Have I got the 

`process.env.PAGE_TTL = 259200;`

In the right place to keep the pages cached?

**Comment by thoop** [comment]
I haven't used the redis prerender cache so I don't know about the PAGE_TTL environment variable.

With the version of node you are on, you'll want to upgrade node and the Prerender server. Our latest Prerender server doesn't run with that old version of node anymore. I'd upgrade node to at least v4 and make sure to use our latest prerender server.

**Comment by benishak** [comment]
does prerender need a lot of CPU power and RAM?
Can I run prerender on EC2 t2nano or t2micro ? we are going to server about 1 million pages

**Comment by thoop** [comment]
In the future, please open a new issue instead of hijacking someone else's open issue.

Yes, Prerender needs lots of CPU and RAM because it uses PhantomJS behind the scenes which is a real web browser. If you have 1 million pages you're probably going to need a couple machines behind a load balancer. Make sure you cache your pages too.

@DanielFitzgerald feel free to reopen this issue if you still have problems after you upgrade as I suspect that's the issue here.

**Comment by DanielFitzgerald** [comment]
@thoop Sorry for delay getting back, upgraded server and it helped. The RAM and CPU now seem to gradually rise though, it takes about ~24 hours for it to max out and crash. 

The only other error I can find in the logs which I haven't posted is 

```
phantom stdout: Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []                                          
http://errors.angularjs.org/1.5.8/$rootScope/infdig?p0=10&p1=%5B%5D     
```

Which seems like an angular error in our code somewhere, we only see it on the prerender server though.

I'll keep digging. It could be the redis plugin not disposing of comments properly. 

Thanks for your help.

**Comment by thoop** [comment]
The Prerender `iterations` and `softIterations` parameters should kill PhantomJS and reclaim that memory. Make sure you have those set low enough so that Prerender keeps restarting itself.

Feel free to reopen if you still run into issues.
