### ISSUE TITLE
504 Errors on Images

### ISSUE THREAD

**Issue by electic** [prerender/prerender#379]
Hi,

Not sure what is wrong with my config. However, I get a ton of 504 errors when it comes to images. I tried this:

http://localhost:3000/https://placecot.com

I am using the standard server.js from source. I would also like to add that it seems pretty slow when I am pulling a page from my local server as well. Any idea what I might be doing wrong? Any help appreciated. 

-R

**Comment by thoop** [comment]
When you load a page like that in your browser, any relative links in the HTML will be loaded from `http://localhost:3000` but the images/css/etc don't live on the Prerender server so that's why you are seeing those 504s.

Once you proxy the HTML through your website with the middleware, you shouldn't see any of those errors because your website will serve all of the relative links just fine.

Feel free to reopen if you continue to see issues after using the middleware, but that's expected behavior when testing directly against the prerender server.

**Comment by electic** [comment]
Any idea on the speed though? It seems to take a long time even for the html to show up?

**Comment by thoop** [comment]
The Prerender server counts the number of requests in flight and saves the pages a short time after that number of requests in flight reaches zero. So speed is very dependent on how fast your website loads all of its resources.

If you turn on the `logRequests` option, you'll see the timing of every request being made and every response being received.
