### ISSUE TITLE
301's not correctly generated

### ISSUE THREAD

**Issue by ChariotIT** [prerender/prerender#385]
I'm running prerender locally to try it out, behind an Nginx server. When I set the 404 prerender-status-code meta tag in my Angular application, the page is rendered correctly and a 404 is returned.

However, I'm redirecting certain pages where the page has been typed incorrectly to the correct page. In Angular I'm doing this with the $location.path() function. Now, I want prerender to generate a 301 on this page, so I've set the prerender-status-code and prerender-header meta tags. However, I'm getting back a 200; the rendered page under the incorrect URL.

$location.path() is only called when the _escaped_fragment_ query parameter is not present. I'm setting the window.prerenderReady variable to true right after I've set the 301 meta tags.

Is there something I'm missing here to correctly return the 301 instead of the 200?

**Comment by thoop** [comment]
The Prerender server does not send `_escaped_fragment_` through to your website when it makes a request so it sounds like you are doing the $location.path() which is clearing out the page to render the new page (causing the meta tags to be removed). You might want to instead check the user agent to see if it contains "Prerender" in order to prevent the redirect.

**Comment by ChariotIT** [comment]
Thanks, that was indeed the issue. This works:
```
if ($window.navigator.userAgent.toLowercase().indexOf("prerender") === -1) {
    $location.path(...);
}
```

**Comment by thoop** [comment]
Great!
