### ISSUE TITLE
How to use the window.prerenderReady method in angular apps?

### ISSUE THREAD

**Issue by chrillewoodz** [prerender/prerender#387]
I'm having difficulties implementing the "ugly hack" that forces prerender to wait until `prerenderReady` is set to `true`, as described here: 

http://stackoverflow.com/questions/42780306/angular-2-how-to-use-prerender-io-along-with-lazy-loading

The issue is that Angular doesn't like inline scripts which makes it hard to implement this solution. Are there any known ways here or am I just screwed completely?

**Comment by thoop** [comment]
You mention that Prerender doesn't appear to wait for lazy loaded modules. Are you waiting for anything in particular to lazy load those modules (page load event, image load event, scrolling event)? Because the Prerender server counts the number of requests in flight and saves the page a short time after that number stays at zero. So loading modules as they are used shouldn't cause any issues there. Can you send us a URL so we can double check that and make sure there isn't another issue? support@prerender.io

According to [this Angular issue](https://github.com/angular/angular/issues/4903), it looks like you can put script tags in the `index.html` and angular2 won't remove them.

**Comment by chrillewoodz** [comment]
I've sent an email to the provided email. We do not wait for anything in particular. The problem is that you can't update anything dynamically in the index file as angular doesn't operate there. You simply put a root component into index and anything in the root component and below in its tree is angular related.

**Comment by kumargauravhcl** [comment]
any answer to it?

**Comment by MikkCed** [comment]
it would be helpful to say why it's closed and preferably mentioning the resolution/work arround
