### ISSUE TITLE
Checks on google punishment.

### ISSUE THREAD

**Issue by lakesare** [prerender/prerender#393]
I feel like a lot of people are wary of using Prerender because of the idea that google punishes sites for rendering different content for google bots (blank page with google's 'Fetch and Render' tool, and full page with Prerender).
Have you done some tests on it maybe, or do you have some other way to disprove it?

**Comment by thoop** [comment]
The `_escaped_fragment_` crawling protocol was built by Google to prevent the need to check Googlebot by their user agent to serve them different content.

As long as you have `<meta name="fragment" content="!">` in the `<head>` of your pages, Googlebot will re-request that URL with the `?_escaped_fragment_=` query parameter. That's Google's way of detecting that you have a prerendered page waiting for them and then requesting that prerendered page.

That way, you will not be penalized for cloaking. We have done plenty of tests on it with all of our customers following the escaped fragment crawling protocol and not running into any issues!

**Comment by alfhen** [comment]
@thoop That might be true, but according to this https://developers.google.com/webmasters/ajax-crawling/docs/getting-started the _escaped_fragment_ will no longer be supported from summer 2018 which is soon. What do you recommend to do instead?

**Comment by thoop** [comment]
Yes, Google recently announced that they will stop requesting escaped fragment URLs in Q2 of 2018. I would recommend that you test your pages in the Fetch and Render tool and try to get your pages rendering correctly there so that Google can execute your javascript and render your pages.

If you are unable to get Google to render your javascript correctly, you could have your Prerender middleware check Googlebot by their user agent to serve a prerendered page. Just make sure you are serving the exact content your users see when they visit your pages.

Prerender is still needed for Bing, Facebook, Twitter, Yandex, Baidu, and other crawlers so it's only Google that will be executing a full javascript page in a browser.
