### ISSUE TITLE
Lots of 504s, confused about server settings

### ISSUE THREAD

**Issue by alexstanbury** [prerender/prerender#396]
Hi, firstly thanks for making this, it's been invaluable in our attempts to make our site rank well. 

We are getting a lot of 504 errors with the reason being given in console that PhantomJS restarted in the middle of the request. Is there a way to avoid this happening?

Here is my server config:

```
PRERENDER_SERVER_PORT=4000
REDIS_URL="redis://localhost:4001/0"
PAGE_TTL=604800
RESOURCE_DOWNLOAD_TIMEOUT=10000
PAGE_DONE_CHECK_TIMEOUT=300
WAIT_AFTER_LAST_REQUEST=2000
JS_TIMEOUT=10000
JS_CHECK_TIMEOUT=2000
NO_JS_EXECUTION_TIMEOUT=3000
EVALUATE_JAVASCRIPT_CHECK_TIMEOUT=300
PHANTOM_CLUSTER_NUM_WORKERS=16
PHANTOM_WORKER_ITERATIONS=500
PHANTOM_WORKER_SOFT_ITERATIONS=100
```

I'm confused between the iterations and softIterations settings and how they work together/against each other, would you mind clarifying how these can be set optimally? 

Is it possible to stagger PhantomJS restarting so they don't all restart at a similar time? The 504s seem to come in batches and it's when all the PhantomJS instances are restarting.

Do any of the settings jump out at you as being the cause?

I'm happy to send you some server logs if that helps.

Server is running Windows Server 2012 with the following specs:

Intel E3-1220 v1 processor (quad core 3.1GHZ from 2011)
32GB RAM
2 X 500GB SSD (RAID 1)

**Comment by thoop** [comment]
`softIterations` and `iterations` both mean how many pages are rendered before the PhantomJS server is restarted. The difference is that `softIterations` tries to wait until there are no pages currently being rendered so that it doesn't interrupt anything. `iterations` does not wait and will shut down PhantomJS while it's rendering a page and cause it to return a 504 for any pages currently being rendered during shutdown. These restarts are to free up RAM that PhantomJS holds onto.

So I would suggest setting `softIterations` to something low like 10 (restart PhantomJS often if no requests are in flight) and set `iterations` to something like 50-100 depending on how much RAM your machine has.

I would recommend setting the number of workers equal to the number of CPUs you have on your machine. If you are still seeing lots of 504s after that, you might be sending too many requests to that Prerender server and might need to start a few Prerender servers behind a load balancer.

That being said, are you using an older version of the Prerender server? Those configs looks like configs from old version of our server.

**Comment by alisinabh** [comment]
@thoop I don't think this problem is caused by iterations and softIterations.
I have this problem too. I believe there is something wrong with phridge (PhantomJS)
Here is my problem info:

By just serving one request correctly other request will face 504 errors:

```
2017-05-05T20:44:49.721Z getting https://manmamanam.com/explainpost.html?PostId=13090&name=میم مثل مد&category=مد و زیبایی&categoryId=13&pageid=62#!/post/12920/کلینیک پوست دکتر زارعی/مد و زیبایی/13/2
2017-05-05T20:44:58.707Z Experiencing infinite javascript loop. Killing phantomjs...
2017-05-05T20:44:58.803Z got 504 in 9297ms for https://manmamanam.com/explainpost.html?PostId=286&pageid=54&category=خانه و خانواده&categoryId=24&name=میم مثل مزرعه#!/post/12257/میم مثل مهربانو/خانه و خانواده/24/52
2017-05-05T20:44:58.851Z PhantomJS restarted in the middle of this request. Aborting...
```


**But when i use service.prerender.io all pages will render.**

Im using master branch by the way. last commit: cb73d8605e

Thanks

**Comment by alexstanbury** [comment]
I think my problem is caused primarily by the number of requests incoming
to the server, our site has a huge amount of pages to index. The repeated
requests mean that there are not enough processes to handle them all and
still have time to restart phantom when it's needed.

**Comment by alisinabh** [comment]
@alexstanbury did you increase iteration time? If so did it work?

Is there any other errors before PhantomJS restart. (In my case there is a infinity loop exception)

**Comment by alexstanbury** [comment]
Increasing iteration values does help but putting it too high causes
phantom to crash more than it already does. I do see phantom errors and
crashes still but I am having to live with the 504s for now in the hope
that next time the page is crawled it will be ok. Not ideal but better than
nothing.

**Comment by thoop** [comment]
@alexstanbury I would suggest using more Prerender servers behind a load balancer. Sounds like you are just sending too many requests to the PhantomJS server. Feel free to use our hosted service as we can handle any scale you need :)

@alisinabh Feel free to open a new issue, I don't think what you are seeing is related to @alexstanbury 's problem

**Comment by alexstanbury** [comment]
@thoop Do you mean using more physical servers or using something like nginx to balance the load between multiple instances of the node app?

**Comment by thoop** [comment]
I mean more physical servers. One prerender server already does start multiple instances of PhantomJS to load balance itself but we recommend only using a number of workers equal to the number of CPUs on the machine. Anything more than that wont improve performance. So if you hit performance issues after scaling workers, you'll need to scale physical servers behind a load balancer.

**Comment by alexstanbury** [comment]
Ok yeah that's what I thought. I'll definitely have to look into it.
Prerender.io is a bit out of our reach at the moment unfortunately or else
we'd be using that.  Thanks for your help!

On 8 May 2017 22:18, "Todd Hooper" <notifications@github.com> wrote:

I mean more physical servers. One prerender server already does start
multiple instances of PhantomJS to load balance itself but we recommend
only using a number of workers equal to the number of CPUs on the machine.
Anything more than that wont improve performance. So if you hit performance
issues after scaling workers, you'll need to scale physical servers behind
a load balancer.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/prerender/prerender/issues/396#issuecomment-299993897>,
or mute the thread

**Comment by alisinabh** [comment]
@thoop I've checked and yes the problem seems to be insufficient memory. Thank you
