### ISSUE TITLE
Returned HTML with no <script> tag at all.

### ISSUE THREAD

**Issue by xyz017048** [prerender/prerender#399]
I've tried using prerender.io and my own heroku server, and they all have the same problem, which is the html that the prerender service returned does not contain any of my script tags. 
My HTML header looks like this: 
![capture](https://cloud.githubusercontent.com/assets/21039886/26504089/ca663156-4208-11e7-9c65-4bcc629f474c.PNG)

But prerender service returned HTML only has the commended part:
![capture2](https://cloud.githubusercontent.com/assets/21039886/26504299/a6a67e96-4209-11e7-9391-4e778a05f290.PNG)

I've tried loading script with async and defer, but it did not make a difference. What could be the problem here? Thanks in advance!

**Comment by thoop** [comment]
The Prerender server is built to remove all <script> tags after the page has been rendered to the HTML. That's because the fully rendered HTML no longer needs the <script> tags and if a crawler were to try to execute the script tags then it might clear out the rendered HTML.

If your app HTML is not being rendered right, it's likely a different issue and most likely a javascript error that's happening when rendering your page. You should see any javascript errors on the Prerender server console if you turn on the logger() plugin.

**Comment by xyz017048** [comment]
Thanks for the quick response! I try using the logger() to debug the app, and it kept getting undefined error(see below). The app works with no error by itself, but prerender could not get it running, I have no idea what the problem might be.

![capture](https://cloud.githubusercontent.com/assets/21039886/26642515/a4141b6e-45f3-11e7-9f25-e4ddaad2d639.PNG)

**Comment by thoop** [comment]
Hmm, hard to say without seeing your website...but from errors I've seen in the past you might be loading `<script>` tags in the `<body>` and they might be loading out of order. Can you try making sure all of your script tags are being loaded in the `<head>`?

Otherwise, the only thing I could think that would cause that would be if you are using any ES6 javascript that PhantomJS might be getting tripped up on. Do you have any ES6 javascript being used?

**Comment by xyz017048** [comment]
I did try loading the scripts in the <head> and also tried using async and defer to load, but the problem remains. About ES6, I am pretty sure we don't have any ES6 syntax in our code, but I didn't write all the code, so I'm not sure. But luckily I've got a solution for what I need. I wrote a jQuery function in the header that gets the information of the page from back end and sets all the meta tags that I need. I'm still testing it, but it seems to be working just fine. Thanks for your help!

**Comment by chrisdevc** [comment]
Hi, we are facing the same issue as the OP, however we are using ES6. Transpiling using [ecmascript](https://docs.meteor.com/packages/ecmascript.html) meteor package.  Also because we have WSS requests, we are delaying caching for 5seconds, ensuring pages are fully rendered. We are doing this using the window.prerenderReady flag. We cannot confirm this is working since we are not getting the full page, cached. (So my thought is that it is failing to cache because of Es6 incompatibility) What are our options ? We can't change the code to use ES < ES6. Thanks in advance

**Comment by thoop** [comment]
We now support ES6 with our Chrome rendering engine. If you are using our hosted service, send us an email and we can switch your account over to use Chrome. You can find more information about that here: https://prerender.io/documentation/chrome-server

**Comment by vinicius91carvalho** [comment]
I have a issue with the URL: https://app.findnear.com.br/loja/sound-store/jbl-vulcano-3-8, @thoop can you help me?

**Comment by thoop** [comment]
@vinicius91carvalho I responded to your email so let's continue the conversation there!
