### ISSUE TITLE
Prerender is slow, took more than 10s for first load

### ISSUE THREAD

**Issue by tinygipxy** [prerender/prerender#409]
Hi, 
I'm running prerender in Centos 7, it's working but very slow, all pages took more than 10s for fistload, anyway to tuning it ?  
....
2017-07-06T04:07:48.391Z got 200 in **21476ms** for https://dev2.landber.com/web/searchdc/bds-cho-thue-huyen-hiep-hoa-bac-giang/1/BG/104/4
...

Thank you

**Comment by thoop** [comment]
That page takes a long time to load in my Chrome browser as well so it might just be a timing issue on your end.

I'd suggest turning on the `logRequests` option on the prerender server in order to print out all of the requests/responses and their timings in order to see what might be causing the long load time.

**Comment by tinygipxy** [comment]
I see, thank you
