### ISSUE TITLE
Add chromium as package dependency

### ISSUE THREAD

**Issue by hensansi** [prerender/prerender#423]
There is a new googleChrome project (puppeteer) that downloads the chromium as dependency. Can we do something similar with prerender?

With this we can easily containerize prerender which was something with what  I was struggling yesterday.

POC:
https://github.com/prerender/prerender/compare/chrome...hensansi:chrome

`docker run -p 3000:3000 hensansi/prerender`

[Dockerfile
](https://github.com/hensansi/dockerfiles/blob/master/prerender/Dockerfile)

**Comment by thoop** [comment]
Yeah the Chromium install is nice.

In the current state of prerender where we are using phantomjs, we downloaded the phantomjs binary every time. This caused lots of problems when downloading the binary for every npm install. We ran into issues where sometimes the downloads would fail in production due to random weirdness with npm or the network.

With our use of Chrome so far with prerender, it works much better to already have Chrome installed on the machine so prerender can be lightweight.

I know that makes prerender a little harder to use but most people should already have Chrome installed when testing locally. So really this just makes it a little harder to deploy prerender.

We won't want to pull puppeteer as a dependency just for the Chromium install.
