### ISSUE TITLE
Stable release channel?

### ISSUE THREAD

**Issue by jonocodes** [prerender/prerender#437]
I would like to host my own prerender for my site, but there seems to be no stable release branch or tags/releases at all. 

How does one determine what point of time or branch to run from this project?

**Comment by thoop** [comment]
In the future, we'll use the github tags/releases to help more there but the master branch is currently the most up to date and stable branch for you to use. Any large development efforts will be done on other branches and merged into master when ready/stable.

In our production Prerender service we pull in and use the latest prerender npm package, so the npm releases are what we use instead of github tags/releases.

**Comment by jonocodes** [comment]
Ok. I will use 'npm show prerender versions' for now to get stable releases from. Thanks.
