### ISSUE TITLE
s3HtmlCache support for chrome branch

### ISSUE THREAD

**Issue by adarshsingh1407** [prerender/prerender#438]
It will be great if we could get the **s3 HTML cache support for chrome branch**. This feature is said to be _coming soon_.

P.S. Can anyone tell me an approximate time for this feature to release?

**Comment by thoop** [comment]
there isn't an ETA yet but it should be really easy for you to pull it over from our master branch if you need it in the meantime and then upgrade once we add it back. I'll leave this issue open until we get that moved over.

**Comment by ethereal-sandeep** [comment]
Hi @thoop , its not there in master branch 
https://github.com/prerender/prerender/blob/master/lib/plugins/s3HtmlCache.js

Also how is the cache expiry handled in s3HtmlCache.

**Comment by thoop** [comment]
Sorry this is an old comment and we've moved Chrome over to our master branch since that was posted.

You should be able to find the s3HtmlCache on the phantomjs2 branch: https://github.com/prerender/prerender/blob/phantomjs/lib/plugins/s3HtmlCache.js

You should be able to copy that code over and just modify the event names:

`beforePhantomRequest` -> `requestReceived`
`afterPhantomRequest` -> `beforeSend `

**Comment by thoop** [comment]
This is now available on its own repo and npm module. Find more information here: https://github.com/prerender/prerender-aws-s3-cache
