### ISSUE TITLE
how to render relative images?

### ISSUE THREAD

**Issue by ghost** [prerender/prerender#44]
often relative images on a webpage show up as broken. is it possible to cache the images in prerender and display them or simply make the relative images into absolute urls. I guess I could do the latter with javascript.

**Comment by johnzw89** [comment]
If I am using the prerender.io service, how can I setup the proxy through my servers to get the relative image paths working?

**Comment by thoop** [comment]
You should proxy the request through your website using the Prerender.io middleware. That way relative images will work fine without changing anything since the domain is correct. If you are just testing directly against your prerender server, the relative images won't work since the domain is different but that shouldn't matter since it will work once proxied through your site.

**Comment by bbnnt** [comment]
@thoop how do you proxy those css/images/etc… ?

**Comment by thoop** [comment]
You shouldn't proxy static files through the Prerender service. You should serve those directly from your server. Email us at support@prerender.io if you have any questions about getting that to work with the middleware.

**Comment by scher200** [comment]
Dear @thoop I like to add that on my angular-cli project I experience the same error both. Relative non-external paths within css files where not loaded correctly:
```
background-image: url('../images/a-green-field.jpg');
```
It was never loaded. I was forced to rewrite my urls with the full path https://www.live-domain.com/images/a-green-field.jpg. This happens during local testing, but also at the online service prerender.io

During testing I tried the following path:
```
http://localhost:3000/http://localhost:4200/images/a-green-field.jpg
```
And the image showed up.

Please let me know if there is any trick to inform the prerender io know that the images are available:

**Comment by thoop** [comment]
You shouldn't need to make that change. Relative links will work just fine when you proxy the HTML through your middleware. What you are seeing is the following:

When you access a Prerender server directly in your browser, like:

`http://localhost:3000/http://localhost:4200/`

The prerender server will render the `http://localhost:4200/` page and return the HTML to your browser. Since your browser is viewing your HTML through the domain of `http://localhost:3000/`, that means any relative links in the HTML of `http://localhost:4200/` will be loaded from `http://localhost:3000/` by your browser. Since those files don't live on the Prerender server, you'll see 504s for those relative URLs.

That's expected and isn't an issue because once that HTML is proxied through your Prerender middleware, the HTML will be shown under the domain of `http://localhost:4200/`, and that's where the relative links will work correctly.

So testing directly against your Prerender server might not show css or images that are relative links but serving the HTML through your middleware will fix that without needing to make any changes.

**Comment by thoop** [comment]
Please feel free to create a new issue if anyone has questions about anything else.
