### ISSUE TITLE
Prerender.io and Angular 4

### ISSUE THREAD

**Issue by sunderkasajal1203** [prerender/prerender#443]
HI

 I am trying to use prerender.io for my angular 4 application but i am not able to render my html pages

followed this
 https://github.com/prerender/prerender/tree/chrome and angular.io/guide/quickstart
 for prerender and angular 4 respectively

I have set up both things on my local Then through cmd i ran the two applications separately on different ports 
localhost:3000 for prerender and
 /localhost:4200 for angular

And then i used this url http://localhost:3000/http://localhost:4200 to render the page but it does not seem to load at allIs prerender.io compatible with Angular 2 and Angular 4 or only with AngularJs?

Regards
Sajal

**Comment by thoop** [comment]
I responded to your email earlier this morning so I'll close this issue but it in case anyone finds this in the future, it looks like the issue was that our Prerender.io server doesn't load images by default and the site was expecting the images to be downloaded before inserting content onto the page.
