### ISSUE TITLE
some issue with new prerender using chrome headless

### ISSUE THREAD

**Issue by simonjoom** [prerender/prerender#445]
i use the new prerender,
i saw some problem. 

I installed and use chromium for debian and for now working great.

first if never the user start node with 'sudo' the chrome cannot start.
Maybe could be good to inform that with sudo it s not working. 

In utils.js
we need to pass renderType with "html" for those like me not using /render in Url 
else some plugins cannot work (like for me removescript tag)
line 41:
 } else {
 return {
                        url: util.getUrl(requestedUrl),
                        renderType: 'html',
                        userAgent: "Prerender",
                        fullpage: false
                }
for me i passed the value Prerender in user agent because my application use it 
.. i don't know what using the new prerender user agent (i didn't check)
i updated the prerender-redis-cache to use this version for who want it.

**Comment by thoop** [comment]
Thanks for that!

Yes, you should not run as root user with sudo. You should use a normal user when starting Prerender so that it uses the same user when starting Chrome.

We defaulted the `renderType` to `html` for the non /render endpoint so that should work now. The default user agent will be the Chrome user agent + ' Prerender (+https://github.com/prerender/prerender)' so you shouldn't need to change the user agent there.

Please let me know if this resolves those issues!

**Comment by simonjoom** [comment]
thanks for answering all is clear 
you can close it

**Comment by thoop** [comment]
Thanks!
