### ISSUE TITLE
Allow forwarding cookies to prerender

### ISSUE THREAD

**Issue by jeerbl** [prerender/prerender#456]
Hi!

It would be nice with Headless Chrome to be able to forward cookies to it. For example, if I am logged in on a website and I generate the PDF out of a page that has different content when logged in, the page being generated will be the "not logged in" page because the cookies are not taken into account.

Is it possible to forward cookies to prerender?

Thanks,
Jerome

**Comment by jeerbl** [comment]
A plugin could do that indeed. Just to be sure we are on the same page, here are a few more details about what I want to achieve.

If my prerender server runs on `example.com`, then I want prerender to get all the cookies that were set earlier on `example.com` and forward them to the Headless Chrome instance. I see you are using express so I guess any cookie that is sent to `example.com` are received by express. My question is, would these cookies received by express be available inside the Headless Chrome?

Thanks for your answers!
Jerome

**Comment by thoop** [comment]
The Prerender server wouldn't be able to automatically get the cookies like you mention but you could manually pull your cookie and specify the cookie in the http request to your Prerender server.

So you would only be able to save a PDF of a webpage behind a login by logging into `example.com` yourself, opening your Chrome dev tools and inspecting the request to pull out the cookie, then passing that cookie into the http request to your Prerender server so that it then uses that cookie when trying to render the PDF of your specific page on `example.com`.

Just wanted to make sure we're talking about the same flow!

**Comment by jeerbl** [comment]
Well each user gets a token when they log in and the page differs to each user so the cookie would have to be passed automatically. Since it is not possible, I guess I would have to send that cookie over with a get parameter and generate the PDF for the URL `example.com?token=gue84983jb983` then using this token in my app if it is there.

That would actually work. Thanks for questioning me I guess I should use the rubber duck debugging method a bit more.

**Comment by thoop** [comment]
So are you generating these PDFs for your users when they request a page?

If your user made a request to `example.com/user1/myfile-123` you could have your express server send a request out to the Prerender server to render `example.com/user1/myfile-123?token=abc` where token would be a one-time use token for that user that you'd generate to keep things somewhat secure.

Otherwise you could grab the cookie and pass that through to the Prerender server after building the cookie plugin but that seems a little insecure to be passing cookies around like that.

**Comment by jeerbl** [comment]
Well basically we have a page with some info on it. Depending on your account you might see data in different currencies, different graphs and we want each user to be able to download a PDF version of this page, the PDF should therefore contain exactly what's on the page, same currency, etc.

There are also some of other pages that are not available if you are not logged in, therefore the PDF from prerender would be empty if prerender is not "logged in".

I guess we could just open the PDF generation URL with some GET parameters containing the token (let's say `examplegeneratePDF.com` is our prerender instance) like:
`https://examplegeneratePDF.com/https://example.com/page?token=usertoken` and handle the `token` GET parameter just as if the user was actually logged in.

That's a way of doing this where we do not store cookies in prerender, the token is used on the fly, never stored in the Headless Chrome instance.

Is this what you had in mind?

Again, thanks!
Jerome

**Comment by thoop** [comment]
Yeah that's more along the lines of what I was thinking!

**Comment by jeerbl** [comment]
Closing the issue, I'll do it myself then. Thanks for your support and great job, I've been using prerender on every project since I discovered it actually existed ;)

**Comment by thoop** [comment]
Thanks! And thanks for using Prerender! 😄
