### ISSUE TITLE
in-memory-cache support for chrome branch

### ISSUE THREAD

**Issue by ethereal-sandeep** [prerender/prerender#469]
It will be great if we could get the in-memory cache support for chrome branch. This feature is said to be coming soon.

P.S. Can anyone tell me an approximate time for this feature to release?

**Comment by thoop** [comment]
Sorry we haven't moved that over yet. We'll get that added sometime soon.

**Comment by shusain** [comment]
Actually using the file system cache plugin that I forked and updated to use the new events here: https://github.com/shusain/prerender-filesystem-cache/commit/08f6b9b8cf35468360980186dacb28a8aa5e25ae  figured since the changes seemed to work there it wouldn't be too hard to make the updates to the events here as well.  This seems to only intercept the initial URL/request but other resources loaded by the initial page aren't loaded from cache, still seems better than nothing if someone needs a short term solution.

**Comment by thoop** [comment]
Here's the in-memory cache for the Chrome branch. Sorry for the long delay here!

https://github.com/prerender/prerender-memory-cache

**Comment by ethereal-sandeep** [comment]
@thoop  Thank you so much.
