### ISSUE TITLE
Use the result of the same tab if the URL is called twice

### ISSUE THREAD

**Issue by MartinVandersteen** [prerender/prerender#477]
I'm under the impression that prerender will open 10 tabs to render an URL even if I ask it to render the same URL 10 times. 
This is getting critical because I get a lot of duplicated calls (because of bad implementation of something on my side) and it quickly adds up.
In my case this is totally my fault and I should just fix the duplicated calls, but I was wondering, is it really hard to check if a tab is currently checking an URL before reopening one? I have no knowledge of Google Chrome API but if someone more knowledgeable tells me that its doable I might go ahead and do a PR for that!

Maybe there are problems or use-cases that I didn't think about though and in that case I'd be glad to hear about it!

Thank you guys

**Comment by thoop** [comment]
It would be nice to be able to do something like that, but I'm afraid the implementation would be pretty complex and end up not being super helpful.

One issue is... if you are able to determine that a different tab is loading the same URL, the "duplicate" process would have to just wait for the other process to finish. It wouldn't be able to follow along with the request to call any of the prerender server plugins that you have set up.

The biggest issue is once you need to scale from 1 to 2+ servers, this feature wouldn't help much anymore since requests could be sent to any other server.

So that would be nice to have but I think in practice any code written towards that goal wouldn't provide much value.

**Comment by MartinVandersteen** [comment]
Ok I get what you're saying about the plugin part, that it could be problematic because rendering the page is not always  the only thing prerender does.
I fixed my duplicate calls problem so I'm ok now anyways!
Will take a look at it in case a great idea pops up but indeed, as you said, it would probably be too complex for the good its doing. 

Thanks for your response!

**Comment by thoop** [comment]
Sure thing!
