### ISSUE TITLE
CSS-in-JS does not work

### ISSUE THREAD

**Issue by screendriver** [prerender/prerender#522]
Could it be that dynamically generated CSS-in-JS does not work with prerender.io? For example if you use [glamorous](https://github.com/paypal/glamorous) or [emotion](https://github.com/emotion-js/emotion) then the cached site in my dashboard looks like as without any Stylesheets applied.

I read in the docs about [removeScriptTags](https://github.com/prerender/prerender#removescripttags) and that is exactly the problem. There are no Stylesheets anymore because the scripts (which include glamorous or emotion) are not included.

**Comment by thoop** [comment]
There isn't currently a way to support this through Prerender.io. Once the Prerender server renders the page to the static HTML, all of the script tags are removed.

The script tags are removed because any crawler visiting that page that tries to execute javascript could cause the javascript to clear out the page and try to render it again from scratch, which would defeat the purpose of prerendering the page since they might not execute javascript correctly or completely.

If you can find a way to insert the CSS rules into the HTML, that would be the best way around this issue.

**Comment by screendriver** [comment]
For everybody that have the same issue: I finally found an very easy solution :sunglasses: (if you use [glamorous](https://github.com/paypal/glamorous) or [glamor](https://github.com/threepointone/glamor))

1. detect at runtime in your Browsers JavaScript code the user agent. If it contains prerender you know that it's not a usual user opening your page
2. if it's prerend just disable the [speedy mode](https://github.com/threepointone/glamor/blob/master/README.md#speedy-mode) by setting it to `false`. It will then add every stylesheet directly in the `<head>` of your site instead of appending CSS rules directly into the browser. 

That's it :grin: It is slower, but just for the prerendering. If a normal user opens now your page everything stays as it was. 

Maybe this should be somewhere in the docs @thoop?

**Comment by thoop** [comment]
Cool! Thanks for following up! If other people continue to run into this problem, we'll add it to our docs.

**Comment by csantos42** [comment]
For anyone looking to fix this with styled-components, the solution was the same as @screendriver posted for galmor. Just add this bit of code to head:

```
<script>
    if (navigator.userAgent.indexOf("prerender") !== -1) {
      window.SC_DISABLE_SPEEDY = true;
    }
</script>
```

**Comment by Zhanadil1509** [comment]
how to fix in style-loader? Prerender cahce dom elements keep for 3 days. In style-loader blob hash not dynamicly. For example:
blob:http://localhost:3000/c9b90c1f-e9c1-49da-a70e-32e50598708a
