### ISSUE TITLE
The open graph is not showing for the first time

### ISSUE THREAD

**Issue by csKangGdcomm** [prerender/prerender#525]
I am using your service and it works well ! Thank you for the free plan.

I have found a small problem while using your product.

First time for the request of the open graph is not working and then I works from second time.

I think that first time, the server cache the HTML and then It doesn’t response especially meta tag for the open graph.

Is there any way to solve the problem? Thank you!
( Is there any way to register all my URL automatically? I am using reactJS and the URL is created dynamically so It looks hard... ) 

I am using Meteor to generate server and client. 

Versions:
dferber_prerender: 2.2.2_3 
Meteor: 1.7.0.3

Thank you!

**Comment by thoop** [comment]
I responded to your email, but it looks like this is due to Facebook not wanting to wait longer than ~5 seconds for a page to render...so if we render a page on the fly and it takes longer than that, then Facebook might not wait long enough for the right content.

If the page is already cached in Prerender.io, we would return it from our server in around 100ms and Facebook would get the right info, so you'll want to make sure your pages are cached as much as possible. You can upload a sitemap.xml or use our recache API to pre-cache those URLs so they're already cached when Facebook requests them.
