### ISSUE TITLE
images 400 bad request

### ISSUE THREAD

**Issue by feof** [prerender/prerender#547]
Hi,
I already know that I should use a middleware, but I would like to know how.

I have this source:

```
const prerender = require('prerender');
var server = prerender({
  chromeFlags: ['--no-sandbox', '--headless', '--disable-gpu', '--remote-debugging-port=9222', '--hide-scrollbars', '--disable-setuid-sandbox']
});
server.start();
```
When I go on: http://51.255.193.3:1337/render?url=https://www.tripendipity.com/ I don't see it because the files: css and images, they  are required directly as: http://51.255.193.3:1337/assets/frontlogo.png, and this link obtain 400 error (bad request)

How can I fix it ?

Thanks

**Comment by thoop** [comment]
Sorry for the delay here!

Your browser will take any relative links from the HTML that the Prerender server returns and will try to load those relative links from the domain being accessed. Since you are accessing your Prerender server directly, the domain that your browser tries to load those relative links from is your Prerender server....and those files do not live on your Prerender server.

So, setting up the middleware is the correct way to get that working. You could always change your HTML to use absolute links with the full domain name instead of just relative links, but you never want a crawler to access your Prerender server directly. You want the crawlers to access your website and then receive the prerendered page directly from your server so that the crawlers send users to your website directly.
