### ISSUE TITLE
Is there a way to start chrome that preserves the chrome cache?

### ISSUE THREAD

**Issue by Yoshi9143** [prerender/prerender#569]
Thanks all for the great software

I notice from other threads that each request opens a new tab like if it were in incognito. The problem is that this wont preserve the cache and will hit my CDN for each javascript & css files (higher expense). Is there a way to start pre-render that it preserves the website cache so that each file doesn't have to be re-downloaded?

**Comment by thoop** [comment]
This is by design since we open separate incognito contexts for each request to prevent cookies, local storage, etc from bleeding over. It would be nice to somehow share the cache between tabs but would require some work to put together, especially sharing a cache between different servers in a cluster.

Are you just worried about the higher costs from your CDN or is your rendering too slow with those extra requests to the CDN?

**Comment by paulincai** [comment]
@Yoshi9143 how about this: [https://forums.meteor.com/t/server-side-rendering-for-seo-improvement/42327/3](url)

**Comment by thoop** [comment]
I think this could be built as a plugin or something to add to Prerender/chrome but isn't currently a priority here. If anyone comes up with something in the future please let us know.
