### ISSUE TITLE
Cache normal request

### ISSUE THREAD

**Issue by acegilz** [prerender/prerender#604]
Using nginx with default config and in-memory cache plugin.

I was thinking about the idea of caching user's regular requests so when bots come later, instead of having to wait, being given automatically with the user's pre-rendered version.

Is there any way to make that on a callback style via nginx ? or what do you recommend?

**Comment by thoop** [comment]
Sorry, I'm not sure of the best way to do that. We cache all of our HTML and then recache that HTML at a later date in order to keep it up to date. That way, we don't have to use a TTL or try to populate the cache on the fly. You might consider just sending requests to your website on a regular basis from a list of known URLs on your site.
