### ISSUE TITLE
Would it be possible to have special `script` tags not removed when using `removeScriptTags`?

### ISSUE THREAD

**Issue by jeerbl** [prerender/prerender#606]
Here is the scenario. I have a VueJS application that I want to have prerendered for caching the generated HTML in Redis. I definitely don't want any VueJS to be executed when it's prerendered but I'd like to be able to specify some VanillaJS to keep some interaction handling in JavaScript.

Like having an attribute on the `script` tags like `<script prerender-no-remove>...</script>`.

**Comment by jmojon** [comment]
@jeerbl have you had a look at the code in removeScriptTags? You should easily be able to tweak it to your needs. Just look at how json+ld is ignored and add a rule some arbitrary variable name or so.

**Comment by jeerbl** [comment]
@jmojon That's what I ended up doing yeah. I am wondering, maybe I could send a pull request for this change?

**Comment by jmojon** [comment]
Sounds like a good idea to me, I'm not involved in this project though. Just saw your question when I was poking around after sending a pull request myself for two other small tweaks.

There hasn't been much activity in this repo lately though.

**Comment by thoop** [comment]
Sorry for the slow response time! We're super busy with our hosted service at https://prerender.io/ and the browser works great for our needs so we haven't been making many changes lately!

Are you looking to leave javascript on the page for certain users? This isn't something we'd really want to add to our open source repo since we haven't seen this become a valid use case yet. The crawlers don't need the javascript to interact with the page and we don't currently serve prerendered pages to users, but you could easily build your own plugin that you can publish separately and use in your own Prerender server.

We might revisit this someday though.
