### ISSUE TITLE
Is it normal / expected that a JS web app would not be interactive when spoofing a crawler?

### ISSUE THREAD

**Issue by vesper8** [prerender/prerender#610]
So when a crawler visits the page, a pre-rendered html snapshot is returned so that it may be easily indexed and crawled by all search engines.. great!

But when testing things out and spoofing search engine crawlers.. is it normal / expected that the page will appear to be broken and non-interactive (I'm talking about a Vue SPA/PWA here). Since there is no logic for transitioning from the pre-rendered html to an interactive Vue web app?

I imagine it's normal.. but just want to double check that this is the expected behaviour and is perfectly fine since the crawlers don't care about interactivity working

**Comment by sbalay** [comment]
Hi @vesper8, yes this is intended.

A short version of the reasons can be found in this comment https://github.com/prerender/prerender/issues/565#issuecomment-454656764

**Comment by vesper8** [comment]
thanks for the reply @sbalay. I suppose this could also sometimes interfere with the screenshot" appearing broken when using "Fetch as GoogleBot" or using Google's Inspect Url and then looking at the screenshot.

Is commenting out `server.use(prerender.removeScriptTags());` from `server.js` a solution for undoing this behaviour of stripping scripts? Not that I necessarily want to do that.. just curious if this would work.. at the risk of the crawler executing the scripts

**Comment by sbalay** [comment]
Hi @vesper8, what you are proposing sounds promising but I can't really say for sure. The solution discussed in this thread may help you as well https://github.com/prerender/prerender/issues/606

**Comment by thoop** [comment]
Thanks @sbalay for the help :)

Yes, @vesper8 that is intended. Leaving the script tags in the page would not solve the issue since anyone executing the javascript would have to re-render the page from scratch by clearing the page out and starting over.

This might one day be resolved with React/Vue using hydrate() to leave the HTML content as rendered instead of rendering from scratch but we aren't there yet.

For now, removing the script tags does not cause any issues with the crawlers since the crawlers don't interact with the page anyways.
