### ISSUE TITLE
Hope add options to cache resources , maybe is seo good idea

### ISSUE THREAD

**Issue by 23233** [prerender/prerender#626]
### Story Card
* Users client and spider want to fast open web site  .
* Front developer want to modernization and high efficiency job work  .

### Description of Requirement
**if this library have cache resources , developer just use hash resources suffix or set expired time ,  client and developer and spider can get what they want most !!**

### Seo Must
now , library is fine ,but use to seo , just unsatisfactory , because use seo , most use self web site , change controllable , singe web site each get all resources , it's stupid !!

**Comment by thoop** [comment]
Hi there! We use a new incognito context for each chrome tab to prevent cookie or cache issues between tabs. Since we use a incognito context, it prevents cache sharing between tabs.

We hope to be able to have a file cache between tabs but don't have anything available yet so each resource needs to be downloaded for each page render.

Sorry for the inconvenience.
